name = "aarengine"
version = "0.1.0"
defaultTargets = ["Main", "Proofs", "aarengine"]
weakLeanArgs = ["-j1"]

[[lean_lib]]
name = "Main"

[[lean_lib]]
name = "Proofs"

[[lean_exe]]
name = "aarengine"
root = "Main"
