name = "aardengine"
version = "0.1.0"
defaultTargets = ["Main", "Proofs", "aardengine"]
weakLeanArgs = ["-j1"]

[[lean_lib]]
name = "Main"

[[lean_lib]]
name = "AARD"

[[lean_lib]]
name = "Proofs"

[[lean_exe]]
name = "aardengine"
root = "Main"
